<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-05 at 21:59:44.
 */
require_once '../../mdl/class.packages.php';
class mdl_packagesTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var mdl_packages
     */
    

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Generated from @assert () != NULL
     */
    public function testUpdatesToPackages()
    {   
        $object = new mdl_packages();
        $_GET['id'] = 4;
        // Remove the following lines when you implement this test.
        $this->assertTrue($object->updatesToPackages() !== NULL);
        echo "Hallo";
    }

    /**
     * @covers mdl_packages::getSpecificPackage
     * @todo   Implement testGetSpecificPackage().
     */
    public function testGetSpecificPackage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers mdl_packages::save
     * @todo   Implement testSave().
     */
    public function testSave()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers mdl_packages::update
     * @todo   Implement testUpdate().
     */
    public function testUpdate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers mdl_packages::delete
     * @todo   Implement testDelete().
     */
    public function testDelete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers mdl_packages::getTypes
     * @todo   Implement testGetTypes().
     */
    public function testGetTypes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers mdl_packages::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
